apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1

  selector:
    matchLabels:
      app: jenkins

  template:
    metadata:
      labels:
        app: jenkins

    spec:
      serviceAccountName: jenkins

      nodeSelector:
        kubernetes.io/hostname: k8s-worker1

      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk21

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "1Gi"

          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home


      volumes:
        - name: jenkins-home
          hostPath:
            path: /var/lib/jenkins-data
            type: Directory

